name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: latest
        run_install: false
        
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-
          
    - name: Install dependencies
      run: pnpm install
      
    - name: Build project
      run: pnpm build
      env:
        VITE_DASHSCOPE_API_KEY: ${{ secrets.VITE_DASHSCOPE_API_KEY }}
        
    - name: Install sshpass
      run: sudo apt-get install -y sshpass
      
    - name: Deploy to server
      run: |
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" \
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
        dist/ ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/usr/share/nginx/html/au/
      env:
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        
    - name: Deployment Status
      run: echo "Deployment completed successfully!"